/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyComponent1: typeof import('./src/components/BodyComponent1.vue')['default']
    BodyComponent2: typeof import('./src/components/BodyComponent2.vue')['default']
    BodyComponent3: typeof import('./src/components/BodyComponent3.vue')['default']
    BodyComponent4: typeof import('./src/components/BodyComponent4.vue')['default']
    BodyHome: typeof import('./src/components/BodyHome.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NumberTicker: typeof import('./src/components/NumberTicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
